/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cotlin.calling.klojure.calling.cotlin
import cckc.lib.klo
import java.util.function.Function

fun main() {
    val f = Function<String, String> { it.filter(Char::isLetter) }
    val urls = listOf("https://github.com", "https://clojuredocs.org", "https://kotlinlang.org")
    val res = klo.funky(urls, f)
    res.forEach {
        println("\n===== " + it.key + " =====" + klo.printer(it.value as List<*>))
    }
}
